<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Penjualan_model extends CI_Model
{

    public $table = 'penjualan';
    public $id = 'id_penjualan';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*, pelanggan.id_pelanggan,user.id_user,marketplace.id_marketplace,status.id_status');
$this->db->join('pelanggan', 'pelanggan.id_pelanggan = penjualan.id_pelanggan', 'left');
$this->db->join('user', 'user.id_user = penjualan.id_user', 'left');
$this->db->join('marketplace', 'marketplace.id_marketplace = penjualan.id_marketplace', 'left');
$this->db->join('status', 'status.id_status = penjualan.id_status', 'left');
$this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*, pelanggan.id_pelanggan,user.id_user,marketplace.id_marketplace,status.id_status');
$this->db->join('pelanggan', 'pelanggan.id_pelanggan = penjualan.id_pelanggan', 'left');
$this->db->join('user', 'user.id_user = penjualan.id_user', 'left');
$this->db->join('marketplace', 'marketplace.id_marketplace = penjualan.id_marketplace', 'left');
$this->db->join('status', 'status.id_status = penjualan.id_status', 'left');
$this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penjualan', $q);
$this->db->select('*, pelanggan.id_pelanggan,user.id_user,marketplace.id_marketplace,status.id_status');
$this->db->join('pelanggan', 'pelanggan.id_pelanggan = penjualan.id_pelanggan', 'left');
$this->db->join('user', 'user.id_user = penjualan.id_user', 'left');
$this->db->join('marketplace', 'marketplace.id_marketplace = penjualan.id_marketplace', 'left');
$this->db->join('status', 'status.id_status = penjualan.id_status', 'left');
	$this->db->or_like('pelanggan.id_pelanggan', $q);
	$this->db->or_like('user.id_user', $q);
	$this->db->or_like('marketplace.id_marketplace', $q);
	$this->db->or_like('status.id_status', $q);
	$this->db->or_like('nomor_invoice', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('sub_total', $q);
	$this->db->or_like('diskon', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('bayar', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penjualan', $q);
$this->db->select('*, pelanggan.id_pelanggan,user.id_user,marketplace.id_marketplace,status.id_status');
$this->db->join('pelanggan', 'pelanggan.id_pelanggan = penjualan.id_pelanggan', 'left');
$this->db->join('user', 'user.id_user = penjualan.id_user', 'left');
$this->db->join('marketplace', 'marketplace.id_marketplace = penjualan.id_marketplace', 'left');
$this->db->join('status', 'status.id_status = penjualan.id_status', 'left');
	$this->db->or_like('pelanggan.id_pelanggan', $q);
	$this->db->or_like('user.id_user', $q);
	$this->db->or_like('marketplace.id_marketplace', $q);
	$this->db->or_like('status.id_status', $q);
	$this->db->or_like('nomor_invoice', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('sub_total', $q);
	$this->db->or_like('diskon', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('bayar', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penjualan_model.php */
/* Location: ./application/models/Penjualan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-12-28 13:23:46 */
/* http://harviacode.com */